name: Artifact demo

on: [push]

jobs:
  artifact_upload:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World" > output.txt
      - uses: actions/upload-artifact@v4
        with:
          name: artifact upload
          path: output.txt
  artifact_download:
    needs: artifact_upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact download
          path: artifact upload
      - run: cat artifact upload/output.txt
