name: Caller Workflow

on:
  push:
    branches: [patch2]


jobs:
  call-workflow:
    # uses: MohideenER/GitHub-with-java-hello-world-with-maven/.github/workflows/reusableworkflow.yml@patch2
    uses: MohideenER/orangehrm-ci-report-demo/.github/workflows/reusablewf-diff-repo.yml@main
   
    with:
      name: "Repo B Trigger"
    secrets:
      REP_KEY: ${{ secrets.E_KEY }}
   
