name: Caller Workflow

on:
  push:
    branches: [patch2]

jobs:
  call-workflow:
    uses: MohideenER/GitHub-with-java-hello-world-with-maven/.github/workflows/reusableworkflow.yml@patch2
    with:
      name: "Repo B Trigger"
