name: Reusable Workflow

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  use-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Print input and secret
        run: |
          echo "Hello, ${{ inputs.name }}!"
          echo "Using secret: ${{ secrets.REPO_KEY }}"
