# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: My First Workflow


on: 
  
  push:
    branches: ["master", 'patch*']
  pull_request:
    branches: [ "master"]
    types: ["opened","synchronize"]

  workflow_dispatch:
env:
  sessionss : demo
    
jobs:
  
  build:
  
    # if: contains(github.head_ref,'patch')
    runs-on: ubuntu-latest
    env:
      name : Mohid

    steps:
    
    - uses: actions/checkout@v4
    
    - name: Started
      run : echo "Hi GitHub... On push check..."
      
    - name : Multi line code
      env:
        onn : Weekly call
      # if: (github.head_ref != 'patch2')
      run : 
            echo "Git"
            echo "Started"
            echo "$name is giving $sessionss on $onn"
     


      
