name: Variables workflow
on:
  workflow_dispatch:
  # push:
  #   branches : ["master","patch2"]
  
# Workflow variable 
env :
  project : Constted
jobs:
  Variable_demo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
# Configuration variable
      # - name: Show Variable
      #   run: echo "$project - Current runing env is ${{ vars.ENV_ID }}"
# Context variable
